#
# Makefile for all kinds of Fingerprint
#

obj-$(CONFIG_MICROARRAY_FINGERPRINT) += microarray_fp/
obj-$(CONFIG_MICROARRAY_TEE_FINGERPRINT) += microarray_fp_tee/
obj-$(CONFIG_CDFINGER_FINGERPRINT) += cdfinger_fp_ree/
obj-$(CONFIG_MTK_FINGERPRINT_FPSENSOR_REE) +=  fpsensor/
obj-$(CONFIG_MTK_CDFINGER_TEE_V2_FINGERPRINT_SUPPORT) 	+=  cdfinger_fp_tee_v2/
obj-$(CONFIG_SILEAD_FP)		+= silead/
