/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */

#ifndef _MTK_LINUX_ION_H
#define _MTK_LINUX_ION_H
enum mtk_ion_heap_type {
	ION_HEAP_TYPE_MULTIMEDIA = 10,
	ION_HEAP_TYPE_FB = 11,
	ION_HEAP_TYPE_MULTIMEDIA_FOR_CAMERA = 12,
	ION_HEAP_TYPE_MULTIMEDIA_SEC = 13,
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
};

#define ION_HEAP_MULTIMEDIA_MASK BIT(ION_HEAP_TYPE_MULTIMEDIA)
#define ION_HEAP_FB_MASK         BIT(ION_HEAP_TYPE_FB)
#define ION_HEAP_CAMERA_MASK BIT(ION_HEAP_TYPE_MULTIMEDIA_FOR_CAMERA)
#define ION_HEAP_MULTIMEDIA_SEC_MASK BIT(ION_HEAP_TYPE_MULTIMEDIA_SEC)

#define ION_NUM_HEAP_IDS (sizeof(unsigned int) * 8)
#endif
/* WARNING: DO NOT EDIT, AUTO-GENERATED CODE - SEE TOP FOR INSTRUCTIONS */
