#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += gc9503v_fwvgaplus_vdo_ips_boe_hanlong_secbatch.o



ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc




