#  SPDX-License-Identifier: GPL-2.0 */




obj-$(CONFIG_MACH_MT6580) += $(subst ",,$(CONFIG_MTK_PLATFORM))/
obj-$(CONFIG_MACH_MT6735) += $(subst ",,$(CONFIG_MTK_PLATFORM))/
obj-$(CONFIG_MACH_MT6735M) += $(subst ",,$(CONFIG_MTK_PLATFORM))/
obj-$(CONFIG_MACH_MT6753) += $(subst ",,$(CONFIG_MTK_PLATFORM))/
obj-$(CONFIG_MACH_MT6580) += spm_v1/
obj-$(CONFIG_MACH_MT6735) += spm_v1/
obj-$(CONFIG_MACH_MT6735M) += spm_v1/
obj-$(CONFIG_MACH_MT6753) += spm_v1/

obj-$(CONFIG_MACH_MT6735) += cpuidle_v1/
obj-$(CONFIG_MACH_MT6735M) += cpuidle_v1/
obj-$(CONFIG_MACH_MT6753) += cpuidle_v1/
obj-$(CONFIG_MACH_MT6580) += cpuidle_v1/
